### ISSUE TITLE
Missing application of snd inside `indexedTree`

### ISSUE THREAD

**Issue by unlocked2412** [RobTrew/prelude-jxa#2]
https://github.com/RobTrew/prelude-jxa/blob/5e84ff4e25c5cfcc591b59be7b39f4123abb8d8a/jsPrelude.js#L1951-L1961

**Comment by unlocked2412** [comment]
First issue I am opening. Seems very convenient :-)

**Comment by RobTrew** [comment]
Thanks ! I've added an index into the tuple.

**Comment by unlocked2412** [comment]
Good ! It's not necessary to import `snd` that way. Closing the issue :-)

**Comment by unlocked2412** [comment]
Good. However, it doesn't return a type `Tree (a, Int)`, yet. This function:

```haskell
mapAccumLTree(
    i => x => [1 + i, [x, {
        index: i
    }]]
)(rootIndex)
```

returns

```haskell
(Traversable t, Enum b, Num b) => t a -> (b, t (a, b))
```

so, getting the second component of that type results in a type error, I think.

I might suggest composing `snd` and `mapAccumLTree`.

**Comment by RobTrew** [comment]
Thanks ! eta-expanded now.  

(Always hubris to edit without testing – I must try to learn that :-))

**Comment by unlocked2412** [comment]
Works perfectly ! Closing the issue :-)

**Comment by unlocked2412** [comment]
Works perfectly ! Closing the issue :-)
