### ISSUE TITLE
Evaluation of `typeName(null)` gives an error.

### ISSUE THREAD

**Issue by unlocked2412** [RobTrew/prelude-jxa#3]
https://github.com/RobTrew/prelude-jxa/blob/353209400b151bef3caf55a8ca74e04a60dc83fa/jsPrelude.js#L4888-L4912

**Comment by unlocked2412** [comment]
Do you think would be good to check for null earlier ?

**Comment by RobTrew** [comment]
Good catch – I've just pushed a change. Let me know if that doesn't seem to fix it.

**Comment by unlocked2412** [comment]
The issue persists. You latest commit didn't reach the repository, I think.

**Comment by RobTrew** [comment]
Thanks !  Should be there now, I think :-)
