### ISSUE TITLE
enumFromThenTo gives incorrect results

### ISSUE THREAD

**Issue by unlocked2412** [RobTrew/prelude-jxa#5]
https://github.com/RobTrew/prelude-jxa/blob/3c933921add6465877ef3f8637594ec681dc473d/jsPrelude.js#L1143-L1153

I've just executed 

`enumFromThenTo(1)(11)(2)`

and got

`[1]`

**Comment by unlocked2412** [comment]
Perhaps, an alternative could be:

```js
// enumFromThenTo :: Int -> Int -> Int -> [Int]
const enumFromThenTo1 = m =>
    // Integer values enumerated from m to n
    // with a step defined by (nxt - m).
    nxt => n => {
        const d = nxt - m;

        return Array.from({
            length: Math.floor(d/n) + 1
        }, (_, i) => m + (n * i));
    };
```

**Comment by RobTrew** [comment]
You were expecting a different return value ?
It should evaluate to the same as [1,11..2] in Haskell, i.e. [1]

but I may be missing your point ?

**Comment by unlocked2412** [comment]
I apologise ! I wonder why I was so sure about the purpose of the last argument. I thought like it was a step. So, I expected:

`[1,3,5,7,9,11]`
