### ISSUE TITLE
Possible bug in `treeLeaves` ?

### ISSUE THREAD

**Issue by unlocked2412** [RobTrew/prelude-jxa#6]
https://github.com/RobTrew/prelude-jxa/blob/8234535d7d260d43c47a7e535d576818e1bbae64/jsPrelude.js#L4757-L4764

I think there is a typo in the following comparison:

```javascript
(0 < nest.length)
```

**Comment by RobTrew** [comment]
Corrected to `(0 < subNest.length)`

Thanks for the catch !
